// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

package com.putridparrot.units;

/**
 * Data Transfer Rate conversion functions
 */
public final class DataTransferRate {
	/**
	 * Bits Per Second conversion functions
	 */
	public static class BitsPerSecond {
		/**
		 * Converts the supplied Bits Per Second value to KiloBits Per Second
		 * @param value The Bits Per Second input value
		 * @return The value in KiloBits Per Second
		 */
		public static double toKiloBitsPerSecond(double value) {
			return value / 1000.0;
		}
		/**
		 * Converts the supplied Bits Per Second value to MegaBits Per Second
		 * @param value The Bits Per Second input value
		 * @return The value in MegaBits Per Second
		 */
		public static double toMegaBitsPerSecond(double value) {
			return value / 1e+6;
		}
		/**
		 * Converts the supplied Bits Per Second value to GigaBits Per Second
		 * @param value The Bits Per Second input value
		 * @return The value in GigaBits Per Second
		 */
		public static double toGigaBitsPerSecond(double value) {
			return value / 1e+9;
		}
		/**
		 * Converts the supplied Bits Per Second value to TeraBits Per Second
		 * @param value The Bits Per Second input value
		 * @return The value in TeraBits Per Second
		 */
		public static double toTeraBitsPerSecond(double value) {
			return value / 1e+12;
		}
		/**
		 * Converts the supplied Bits Per Second value to KiloBytes Per Second
		 * @param value The Bits Per Second input value
		 * @return The value in KiloBytes Per Second
		 */
		public static double toKiloBytesPerSecond(double value) {
			return value / 8000.0;
		}
		/**
		 * Converts the supplied Bits Per Second value to MegaBytes Per Second
		 * @param value The Bits Per Second input value
		 * @return The value in MegaBytes Per Second
		 */
		public static double toMegaBytesPerSecond(double value) {
			return value / 8e+6;
		}
		/**
		 * Converts the supplied Bits Per Second value to GigaBytes Per Second
		 * @param value The Bits Per Second input value
		 * @return The value in GigaBytes Per Second
		 */
		public static double toGigaBytesPerSecond(double value) {
			return value / 8e+9;
		}
		/**
		 * Converts the supplied Bits Per Second value to TeraBytes Per Second
		 * @param value The Bits Per Second input value
		 * @return The value in TeraBytes Per Second
		 */
		public static double toTeraBytesPerSecond(double value) {
			return value / 8e+12;
		}
		/**
		 * Converts the supplied Bits Per Second value to Kibibits Per Second
		 * @param value The Bits Per Second input value
		 * @return The value in Kibibits Per Second
		 */
		public static double toKibibitsPerSecond(double value) {
			return value / 1024.0;
		}
		/**
		 * Converts the supplied Bits Per Second value to Mebibits Per Second
		 * @param value The Bits Per Second input value
		 * @return The value in Mebibits Per Second
		 */
		public static double toMebibitsPerSecond(double value) {
			return value / 1048576.0;
		}
	}
	/**
	 * GigaBits Per Second conversion functions
	 */
	public static class GigaBitsPerSecond {
		/**
		 * Converts the supplied GigaBits Per Second value to Bits Per Second
		 * @param value The GigaBits Per Second input value
		 * @return The value in Bits Per Second
		 */
		public static double toBitsPerSecond(double value) {
			return value * 1e+9;
		}
		/**
		 * Converts the supplied GigaBits Per Second value to KiloBits Per Second
		 * @param value The GigaBits Per Second input value
		 * @return The value in KiloBits Per Second
		 */
		public static double toKiloBitsPerSecond(double value) {
			return value * 1e+6;
		}
		/**
		 * Converts the supplied GigaBits Per Second value to MegaBits Per Second
		 * @param value The GigaBits Per Second input value
		 * @return The value in MegaBits Per Second
		 */
		public static double toMegaBitsPerSecond(double value) {
			return value * 1000.0;
		}
		/**
		 * Converts the supplied GigaBits Per Second value to TeraBits Per Second
		 * @param value The GigaBits Per Second input value
		 * @return The value in TeraBits Per Second
		 */
		public static double toTeraBitsPerSecond(double value) {
			return value / 1000.0;
		}
		/**
		 * Converts the supplied GigaBits Per Second value to KiloBytes Per Second
		 * @param value The GigaBits Per Second input value
		 * @return The value in KiloBytes Per Second
		 */
		public static double toKiloBytesPerSecond(double value) {
			return value * 125000.0;
		}
		/**
		 * Converts the supplied GigaBits Per Second value to MegaBytes Per Second
		 * @param value The GigaBits Per Second input value
		 * @return The value in MegaBytes Per Second
		 */
		public static double toMegaBytesPerSecond(double value) {
			return value * 125.0;
		}
		/**
		 * Converts the supplied GigaBits Per Second value to GigaBytes Per Second
		 * @param value The GigaBits Per Second input value
		 * @return The value in GigaBytes Per Second
		 */
		public static double toGigaBytesPerSecond(double value) {
			return value / 8.0;
		}
		/**
		 * Converts the supplied GigaBits Per Second value to TeraBytes Per Second
		 * @param value The GigaBits Per Second input value
		 * @return The value in TeraBytes Per Second
		 */
		public static double toTeraBytesPerSecond(double value) {
			return value / 8000.0;
		}
		/**
		 * Converts the supplied GigaBits Per Second value to Kibibits Per Second
		 * @param value The GigaBits Per Second input value
		 * @return The value in Kibibits Per Second
		 */
		public static double toKibibitsPerSecond(double value) {
			return value * 976562.5;
		}
		/**
		 * Converts the supplied GigaBits Per Second value to Mebibits Per Second
		 * @param value The GigaBits Per Second input value
		 * @return The value in Mebibits Per Second
		 */
		public static double toMebibitsPerSecond(double value) {
			return value * 954.0;
		}
	}
	/**
	 * GigaBytes Per Second conversion functions
	 */
	public static class GigaBytesPerSecond {
		/**
		 * Converts the supplied GigaBytes Per Second value to Bits Per Second
		 * @param value The GigaBytes Per Second input value
		 * @return The value in Bits Per Second
		 */
		public static double toBitsPerSecond(double value) {
			return value * 8e+9;
		}
		/**
		 * Converts the supplied GigaBytes Per Second value to KiloBits Per Second
		 * @param value The GigaBytes Per Second input value
		 * @return The value in KiloBits Per Second
		 */
		public static double toKiloBitsPerSecond(double value) {
			return value * 8e+6;
		}
		/**
		 * Converts the supplied GigaBytes Per Second value to MegaBits Per Second
		 * @param value The GigaBytes Per Second input value
		 * @return The value in MegaBits Per Second
		 */
		public static double toMegaBitsPerSecond(double value) {
			return value * 8000.0;
		}
		/**
		 * Converts the supplied GigaBytes Per Second value to GigaBits Per Second
		 * @param value The GigaBytes Per Second input value
		 * @return The value in GigaBits Per Second
		 */
		public static double toGigaBitsPerSecond(double value) {
			return value * 8.0;
		}
		/**
		 * Converts the supplied GigaBytes Per Second value to TeraBits Per Second
		 * @param value The GigaBytes Per Second input value
		 * @return The value in TeraBits Per Second
		 */
		public static double toTeraBitsPerSecond(double value) {
			return value / 125.0;
		}
		/**
		 * Converts the supplied GigaBytes Per Second value to KiloBytes Per Second
		 * @param value The GigaBytes Per Second input value
		 * @return The value in KiloBytes Per Second
		 */
		public static double toKiloBytesPerSecond(double value) {
			return value * 1e+6;
		}
		/**
		 * Converts the supplied GigaBytes Per Second value to MegaBytes Per Second
		 * @param value The GigaBytes Per Second input value
		 * @return The value in MegaBytes Per Second
		 */
		public static double toMegaBytesPerSecond(double value) {
			return value * 1000.0;
		}
		/**
		 * Converts the supplied GigaBytes Per Second value to TeraBytes Per Second
		 * @param value The GigaBytes Per Second input value
		 * @return The value in TeraBytes Per Second
		 */
		public static double toTeraBytesPerSecond(double value) {
			return value / 1000.0;
		}
		/**
		 * Converts the supplied GigaBytes Per Second value to Kibibits Per Second
		 * @param value The GigaBytes Per Second input value
		 * @return The value in Kibibits Per Second
		 */
		public static double toKibibitsPerSecond(double value) {
			return value * 7812500.0;
		}
		/**
		 * Converts the supplied GigaBytes Per Second value to Mebibits Per Second
		 * @param value The GigaBytes Per Second input value
		 * @return The value in Mebibits Per Second
		 */
		public static double toMebibitsPerSecond(double value) {
			return value * 7629.39;
		}
	}
	/**
	 * Kibibits Per Second conversion functions
	 */
	public static class KibibitsPerSecond {
		/**
		 * Converts the supplied Kibibits Per Second value to Bits Per Second
		 * @param value The Kibibits Per Second input value
		 * @return The value in Bits Per Second
		 */
		public static double toBitsPerSecond(double value) {
			return value * 1024.0;
		}
		/**
		 * Converts the supplied Kibibits Per Second value to KiloBits Per Second
		 * @param value The Kibibits Per Second input value
		 * @return The value in KiloBits Per Second
		 */
		public static double toKiloBitsPerSecond(double value) {
			return value * 1.024;
		}
		/**
		 * Converts the supplied Kibibits Per Second value to MegaBits Per Second
		 * @param value The Kibibits Per Second input value
		 * @return The value in MegaBits Per Second
		 */
		public static double toMegaBitsPerSecond(double value) {
			return value / 976.563;
		}
		/**
		 * Converts the supplied Kibibits Per Second value to GigaBits Per Second
		 * @param value The Kibibits Per Second input value
		 * @return The value in GigaBits Per Second
		 */
		public static double toGigaBitsPerSecond(double value) {
			return value / 976562.5;
		}
		/**
		 * Converts the supplied Kibibits Per Second value to TeraBits Per Second
		 * @param value The Kibibits Per Second input value
		 * @return The value in TeraBits Per Second
		 */
		public static double toTeraBitsPerSecond(double value) {
			return value / 976562500.0;
		}
		/**
		 * Converts the supplied Kibibits Per Second value to KiloBytes Per Second
		 * @param value The Kibibits Per Second input value
		 * @return The value in KiloBytes Per Second
		 */
		public static double toKiloBytesPerSecond(double value) {
			return value / 7.812;
		}
		/**
		 * Converts the supplied Kibibits Per Second value to MegaBytes Per Second
		 * @param value The Kibibits Per Second input value
		 * @return The value in MegaBytes Per Second
		 */
		public static double toMegaBytesPerSecond(double value) {
			return value / 7812.5;
		}
		/**
		 * Converts the supplied Kibibits Per Second value to GigaBytes Per Second
		 * @param value The Kibibits Per Second input value
		 * @return The value in GigaBytes Per Second
		 */
		public static double toGigaBytesPerSecond(double value) {
			return value / 7812500.0;
		}
		/**
		 * Converts the supplied Kibibits Per Second value to TeraBytes Per Second
		 * @param value The Kibibits Per Second input value
		 * @return The value in TeraBytes Per Second
		 */
		public static double toTeraBytesPerSecond(double value) {
			return value / 7812500000.0;
		}
		/**
		 * Converts the supplied Kibibits Per Second value to Mebibits Per Second
		 * @param value The Kibibits Per Second input value
		 * @return The value in Mebibits Per Second
		 */
		public static double toMebibitsPerSecond(double value) {
			return value / 1024.0;
		}
	}
	/**
	 * KiloBits Per Second conversion functions
	 */
	public static class KiloBitsPerSecond {
		/**
		 * Converts the supplied KiloBits Per Second value to Bits Per Second
		 * @param value The KiloBits Per Second input value
		 * @return The value in Bits Per Second
		 */
		public static double toBitsPerSecond(double value) {
			return value * 1000.0;
		}
		/**
		 * Converts the supplied KiloBits Per Second value to MegaBits Per Second
		 * @param value The KiloBits Per Second input value
		 * @return The value in MegaBits Per Second
		 */
		public static double toMegaBitsPerSecond(double value) {
			return value / 1000.0;
		}
		/**
		 * Converts the supplied KiloBits Per Second value to GigaBits Per Second
		 * @param value The KiloBits Per Second input value
		 * @return The value in GigaBits Per Second
		 */
		public static double toGigaBitsPerSecond(double value) {
			return value / 1e+6;
		}
		/**
		 * Converts the supplied KiloBits Per Second value to TeraBits Per Second
		 * @param value The KiloBits Per Second input value
		 * @return The value in TeraBits Per Second
		 */
		public static double toTeraBitsPerSecond(double value) {
			return value / 1e+9;
		}
		/**
		 * Converts the supplied KiloBits Per Second value to KiloBytes Per Second
		 * @param value The KiloBits Per Second input value
		 * @return The value in KiloBytes Per Second
		 */
		public static double toKiloBytesPerSecond(double value) {
			return value / 8.0;
		}
		/**
		 * Converts the supplied KiloBits Per Second value to MegaBytes Per Second
		 * @param value The KiloBits Per Second input value
		 * @return The value in MegaBytes Per Second
		 */
		public static double toMegaBytesPerSecond(double value) {
			return value / 8000.0;
		}
		/**
		 * Converts the supplied KiloBits Per Second value to GigaBytes Per Second
		 * @param value The KiloBits Per Second input value
		 * @return The value in GigaBytes Per Second
		 */
		public static double toGigaBytesPerSecond(double value) {
			return value / 8e+6;
		}
		/**
		 * Converts the supplied KiloBits Per Second value to TeraBytes Per Second
		 * @param value The KiloBits Per Second input value
		 * @return The value in TeraBytes Per Second
		 */
		public static double toTeraBytesPerSecond(double value) {
			return value / 8e+9;
		}
		/**
		 * Converts the supplied KiloBits Per Second value to Kibibits Per Second
		 * @param value The KiloBits Per Second input value
		 * @return The value in Kibibits Per Second
		 */
		public static double toKibibitsPerSecond(double value) {
			return value / 1.024;
		}
		/**
		 * Converts the supplied KiloBits Per Second value to Mebibits Per Second
		 * @param value The KiloBits Per Second input value
		 * @return The value in Mebibits Per Second
		 */
		public static double toMebibitsPerSecond(double value) {
			return value / 1048.58;
		}
	}
	/**
	 * KiloBytes Per Second conversion functions
	 */
	public static class KiloBytesPerSecond {
		/**
		 * Converts the supplied KiloBytes Per Second value to Bits Per Second
		 * @param value The KiloBytes Per Second input value
		 * @return The value in Bits Per Second
		 */
		public static double toBitsPerSecond(double value) {
			return value * 8000.0;
		}
		/**
		 * Converts the supplied KiloBytes Per Second value to KiloBits Per Second
		 * @param value The KiloBytes Per Second input value
		 * @return The value in KiloBits Per Second
		 */
		public static double toKiloBitsPerSecond(double value) {
			return value * 8.0;
		}
		/**
		 * Converts the supplied KiloBytes Per Second value to MegaBits Per Second
		 * @param value The KiloBytes Per Second input value
		 * @return The value in MegaBits Per Second
		 */
		public static double toMegaBitsPerSecond(double value) {
			return value / 125.0;
		}
		/**
		 * Converts the supplied KiloBytes Per Second value to GigaBits Per Second
		 * @param value The KiloBytes Per Second input value
		 * @return The value in GigaBits Per Second
		 */
		public static double toGigaBitsPerSecond(double value) {
			return value / 125000.0;
		}
		/**
		 * Converts the supplied KiloBytes Per Second value to TeraBits Per Second
		 * @param value The KiloBytes Per Second input value
		 * @return The value in TeraBits Per Second
		 */
		public static double toTeraBitsPerSecond(double value) {
			return value / 1.25e+8;
		}
		/**
		 * Converts the supplied KiloBytes Per Second value to MegaBytes Per Second
		 * @param value The KiloBytes Per Second input value
		 * @return The value in MegaBytes Per Second
		 */
		public static double toMegaBytesPerSecond(double value) {
			return value / 1000.0;
		}
		/**
		 * Converts the supplied KiloBytes Per Second value to GigaBytes Per Second
		 * @param value The KiloBytes Per Second input value
		 * @return The value in GigaBytes Per Second
		 */
		public static double toGigaBytesPerSecond(double value) {
			return value / 1e+6;
		}
		/**
		 * Converts the supplied KiloBytes Per Second value to TeraBytes Per Second
		 * @param value The KiloBytes Per Second input value
		 * @return The value in TeraBytes Per Second
		 */
		public static double toTeraBytesPerSecond(double value) {
			return value / 1e+9;
		}
		/**
		 * Converts the supplied KiloBytes Per Second value to Kibibits Per Second
		 * @param value The KiloBytes Per Second input value
		 * @return The value in Kibibits Per Second
		 */
		public static double toKibibitsPerSecond(double value) {
			return value * 7.812;
		}
		/**
		 * Converts the supplied KiloBytes Per Second value to Mebibits Per Second
		 * @param value The KiloBytes Per Second input value
		 * @return The value in Mebibits Per Second
		 */
		public static double toMebibitsPerSecond(double value) {
			return value * 0.00762939;
		}
	}
	/**
	 * Mebibits Per Second conversion functions
	 */
	public static class MebibitsPerSecond {
		/**
		 * Converts the supplied Mebibits Per Second value to Bits Per Second
		 * @param value The Mebibits Per Second input value
		 * @return The value in Bits Per Second
		 */
		public static double toBitsPerSecond(double value) {
			return value * 1048576.0;
		}
		/**
		 * Converts the supplied Mebibits Per Second value to KiloBits Per Second
		 * @param value The Mebibits Per Second input value
		 * @return The value in KiloBits Per Second
		 */
		public static double toKiloBitsPerSecond(double value) {
			return value * 1048.58;
		}
		/**
		 * Converts the supplied Mebibits Per Second value to MegaBits Per Second
		 * @param value The Mebibits Per Second input value
		 * @return The value in MegaBits Per Second
		 */
		public static double toMegaBitsPerSecond(double value) {
			return value * 1.04858;
		}
		/**
		 * Converts the supplied Mebibits Per Second value to GigaBits Per Second
		 * @param value The Mebibits Per Second input value
		 * @return The value in GigaBits Per Second
		 */
		public static double toGigaBitsPerSecond(double value) {
			return value / 954.0;
		}
		/**
		 * Converts the supplied Mebibits Per Second value to TeraBits Per Second
		 * @param value The Mebibits Per Second input value
		 * @return The value in TeraBits Per Second
		 */
		public static double toTeraBitsPerSecond(double value) {
			return value / 953674.0;
		}
		/**
		 * Converts the supplied Mebibits Per Second value to KiloBytes Per Second
		 * @param value The Mebibits Per Second input value
		 * @return The value in KiloBytes Per Second
		 */
		public static double toKiloBytesPerSecond(double value) {
			return value / 0.00762939;
		}
		/**
		 * Converts the supplied Mebibits Per Second value to MegaBytes Per Second
		 * @param value The Mebibits Per Second input value
		 * @return The value in MegaBytes Per Second
		 */
		public static double toMegaBytesPerSecond(double value) {
			return value / 7.62939;
		}
		/**
		 * Converts the supplied Mebibits Per Second value to GigaBytes Per Second
		 * @param value The Mebibits Per Second input value
		 * @return The value in GigaBytes Per Second
		 */
		public static double toGigaBytesPerSecond(double value) {
			return value / 7629.39;
		}
		/**
		 * Converts the supplied Mebibits Per Second value to TeraBytes Per Second
		 * @param value The Mebibits Per Second input value
		 * @return The value in TeraBytes Per Second
		 */
		public static double toTeraBytesPerSecond(double value) {
			return value * 0.000000131072;
		}
		/**
		 * Converts the supplied Mebibits Per Second value to Kibibits Per Second
		 * @param value The Mebibits Per Second input value
		 * @return The value in Kibibits Per Second
		 */
		public static double toKibibitsPerSecond(double value) {
			return value * 1024.0;
		}
	}
	/**
	 * MegaBits Per Second conversion functions
	 */
	public static class MegaBitsPerSecond {
		/**
		 * Converts the supplied MegaBits Per Second value to Bits Per Second
		 * @param value The MegaBits Per Second input value
		 * @return The value in Bits Per Second
		 */
		public static double toBitsPerSecond(double value) {
			return value * 1e+6;
		}
		/**
		 * Converts the supplied MegaBits Per Second value to KiloBits Per Second
		 * @param value The MegaBits Per Second input value
		 * @return The value in KiloBits Per Second
		 */
		public static double toKiloBitsPerSecond(double value) {
			return value * 1000.0;
		}
		/**
		 * Converts the supplied MegaBits Per Second value to GigaBits Per Second
		 * @param value The MegaBits Per Second input value
		 * @return The value in GigaBits Per Second
		 */
		public static double toGigaBitsPerSecond(double value) {
			return value / 1000.0;
		}
		/**
		 * Converts the supplied MegaBits Per Second value to TeraBits Per Second
		 * @param value The MegaBits Per Second input value
		 * @return The value in TeraBits Per Second
		 */
		public static double toTeraBitsPerSecond(double value) {
			return value / 1e+6;
		}
		/**
		 * Converts the supplied MegaBits Per Second value to KiloBytes Per Second
		 * @param value The MegaBits Per Second input value
		 * @return The value in KiloBytes Per Second
		 */
		public static double toKiloBytesPerSecond(double value) {
			return value * 125.0;
		}
		/**
		 * Converts the supplied MegaBits Per Second value to MegaBytes Per Second
		 * @param value The MegaBits Per Second input value
		 * @return The value in MegaBytes Per Second
		 */
		public static double toMegaBytesPerSecond(double value) {
			return value / 8.0;
		}
		/**
		 * Converts the supplied MegaBits Per Second value to GigaBytes Per Second
		 * @param value The MegaBits Per Second input value
		 * @return The value in GigaBytes Per Second
		 */
		public static double toGigaBytesPerSecond(double value) {
			return value / 8000.0;
		}
		/**
		 * Converts the supplied MegaBits Per Second value to TeraBytes Per Second
		 * @param value The MegaBits Per Second input value
		 * @return The value in TeraBytes Per Second
		 */
		public static double toTeraBytesPerSecond(double value) {
			return value / 8e+6;
		}
		/**
		 * Converts the supplied MegaBits Per Second value to Kibibits Per Second
		 * @param value The MegaBits Per Second input value
		 * @return The value in Kibibits Per Second
		 */
		public static double toKibibitsPerSecond(double value) {
			return value * 976.563;
		}
		/**
		 * Converts the supplied MegaBits Per Second value to Mebibits Per Second
		 * @param value The MegaBits Per Second input value
		 * @return The value in Mebibits Per Second
		 */
		public static double toMebibitsPerSecond(double value) {
			return value / 1.04858;
		}
	}
	/**
	 * MegaBytes Per Second conversion functions
	 */
	public static class MegaBytesPerSecond {
		/**
		 * Converts the supplied MegaBytes Per Second value to Bits Per Second
		 * @param value The MegaBytes Per Second input value
		 * @return The value in Bits Per Second
		 */
		public static double toBitsPerSecond(double value) {
			return value * 8e+6;
		}
		/**
		 * Converts the supplied MegaBytes Per Second value to KiloBits Per Second
		 * @param value The MegaBytes Per Second input value
		 * @return The value in KiloBits Per Second
		 */
		public static double toKiloBitsPerSecond(double value) {
			return value * 8000.0;
		}
		/**
		 * Converts the supplied MegaBytes Per Second value to MegaBits Per Second
		 * @param value The MegaBytes Per Second input value
		 * @return The value in MegaBits Per Second
		 */
		public static double toMegaBitsPerSecond(double value) {
			return value * 8.0;
		}
		/**
		 * Converts the supplied MegaBytes Per Second value to GigaBits Per Second
		 * @param value The MegaBytes Per Second input value
		 * @return The value in GigaBits Per Second
		 */
		public static double toGigaBitsPerSecond(double value) {
			return value / 125.0;
		}
		/**
		 * Converts the supplied MegaBytes Per Second value to TeraBits Per Second
		 * @param value The MegaBytes Per Second input value
		 * @return The value in TeraBits Per Second
		 */
		public static double toTeraBitsPerSecond(double value) {
			return value / 125000.0;
		}
		/**
		 * Converts the supplied MegaBytes Per Second value to KiloBytes Per Second
		 * @param value The MegaBytes Per Second input value
		 * @return The value in KiloBytes Per Second
		 */
		public static double toKiloBytesPerSecond(double value) {
			return value * 1000.0;
		}
		/**
		 * Converts the supplied MegaBytes Per Second value to GigaBytes Per Second
		 * @param value The MegaBytes Per Second input value
		 * @return The value in GigaBytes Per Second
		 */
		public static double toGigaBytesPerSecond(double value) {
			return value / 1000.0;
		}
		/**
		 * Converts the supplied MegaBytes Per Second value to TeraBytes Per Second
		 * @param value The MegaBytes Per Second input value
		 * @return The value in TeraBytes Per Second
		 */
		public static double toTeraBytesPerSecond(double value) {
			return value / 1e+6;
		}
		/**
		 * Converts the supplied MegaBytes Per Second value to Kibibits Per Second
		 * @param value The MegaBytes Per Second input value
		 * @return The value in Kibibits Per Second
		 */
		public static double toKibibitsPerSecond(double value) {
			return value * 7812.5;
		}
		/**
		 * Converts the supplied MegaBytes Per Second value to Mebibits Per Second
		 * @param value The MegaBytes Per Second input value
		 * @return The value in Mebibits Per Second
		 */
		public static double toMebibitsPerSecond(double value) {
			return value * 7.62939;
		}
	}
	/**
	 * TeraBits Per Second conversion functions
	 */
	public static class TeraBitsPerSecond {
		/**
		 * Converts the supplied TeraBits Per Second value to Bits Per Second
		 * @param value The TeraBits Per Second input value
		 * @return The value in Bits Per Second
		 */
		public static double toBitsPerSecond(double value) {
			return value * 1e+12;
		}
		/**
		 * Converts the supplied TeraBits Per Second value to KiloBits Per Second
		 * @param value The TeraBits Per Second input value
		 * @return The value in KiloBits Per Second
		 */
		public static double toKiloBitsPerSecond(double value) {
			return value * 1e+9;
		}
		/**
		 * Converts the supplied TeraBits Per Second value to MegaBits Per Second
		 * @param value The TeraBits Per Second input value
		 * @return The value in MegaBits Per Second
		 */
		public static double toMegaBitsPerSecond(double value) {
			return value * 1e+6;
		}
		/**
		 * Converts the supplied TeraBits Per Second value to GigaBits Per Second
		 * @param value The TeraBits Per Second input value
		 * @return The value in GigaBits Per Second
		 */
		public static double toGigaBitsPerSecond(double value) {
			return value * 1000.0;
		}
		/**
		 * Converts the supplied TeraBits Per Second value to KiloBytes Per Second
		 * @param value The TeraBits Per Second input value
		 * @return The value in KiloBytes Per Second
		 */
		public static double toKiloBytesPerSecond(double value) {
			return value * 1.25e+8;
		}
		/**
		 * Converts the supplied TeraBits Per Second value to MegaBytes Per Second
		 * @param value The TeraBits Per Second input value
		 * @return The value in MegaBytes Per Second
		 */
		public static double toMegaBytesPerSecond(double value) {
			return value * 125000.0;
		}
		/**
		 * Converts the supplied TeraBits Per Second value to GigaBytes Per Second
		 * @param value The TeraBits Per Second input value
		 * @return The value in GigaBytes Per Second
		 */
		public static double toGigaBytesPerSecond(double value) {
			return value * 125.0;
		}
		/**
		 * Converts the supplied TeraBits Per Second value to TeraBytes Per Second
		 * @param value The TeraBits Per Second input value
		 * @return The value in TeraBytes Per Second
		 */
		public static double toTeraBytesPerSecond(double value) {
			return value / 8.0;
		}
		/**
		 * Converts the supplied TeraBits Per Second value to Kibibits Per Second
		 * @param value The TeraBits Per Second input value
		 * @return The value in Kibibits Per Second
		 */
		public static double toKibibitsPerSecond(double value) {
			return value * 976562500.0;
		}
		/**
		 * Converts the supplied TeraBits Per Second value to Mebibits Per Second
		 * @param value The TeraBits Per Second input value
		 * @return The value in Mebibits Per Second
		 */
		public static double toMebibitsPerSecond(double value) {
			return value * 953674.0;
		}
	}
	/**
	 * TeraBytes Per Second conversion functions
	 */
	public static class TeraBytesPerSecond {
		/**
		 * Converts the supplied TeraBytes Per Second value to Bits Per Second
		 * @param value The TeraBytes Per Second input value
		 * @return The value in Bits Per Second
		 */
		public static double toBitsPerSecond(double value) {
			return value * 8e+12;
		}
		/**
		 * Converts the supplied TeraBytes Per Second value to KiloBits Per Second
		 * @param value The TeraBytes Per Second input value
		 * @return The value in KiloBits Per Second
		 */
		public static double toKiloBitsPerSecond(double value) {
			return value * 8e+9;
		}
		/**
		 * Converts the supplied TeraBytes Per Second value to MegaBits Per Second
		 * @param value The TeraBytes Per Second input value
		 * @return The value in MegaBits Per Second
		 */
		public static double toMegaBitsPerSecond(double value) {
			return value * 8e+6;
		}
		/**
		 * Converts the supplied TeraBytes Per Second value to GigaBits Per Second
		 * @param value The TeraBytes Per Second input value
		 * @return The value in GigaBits Per Second
		 */
		public static double toGigaBitsPerSecond(double value) {
			return value * 8000.0;
		}
		/**
		 * Converts the supplied TeraBytes Per Second value to TeraBits Per Second
		 * @param value The TeraBytes Per Second input value
		 * @return The value in TeraBits Per Second
		 */
		public static double toTeraBitsPerSecond(double value) {
			return value * 8.0;
		}
		/**
		 * Converts the supplied TeraBytes Per Second value to KiloBytes Per Second
		 * @param value The TeraBytes Per Second input value
		 * @return The value in KiloBytes Per Second
		 */
		public static double toKiloBytesPerSecond(double value) {
			return value * 1e+9;
		}
		/**
		 * Converts the supplied TeraBytes Per Second value to MegaBytes Per Second
		 * @param value The TeraBytes Per Second input value
		 * @return The value in MegaBytes Per Second
		 */
		public static double toMegaBytesPerSecond(double value) {
			return value * 1e+6;
		}
		/**
		 * Converts the supplied TeraBytes Per Second value to GigaBytes Per Second
		 * @param value The TeraBytes Per Second input value
		 * @return The value in GigaBytes Per Second
		 */
		public static double toGigaBytesPerSecond(double value) {
			return value * 1000.0;
		}
		/**
		 * Converts the supplied TeraBytes Per Second value to Kibibits Per Second
		 * @param value The TeraBytes Per Second input value
		 * @return The value in Kibibits Per Second
		 */
		public static double toKibibitsPerSecond(double value) {
			return value * 7812500000.0;
		}
		/**
		 * Converts the supplied TeraBytes Per Second value to Mebibits Per Second
		 * @param value The TeraBytes Per Second input value
		 * @return The value in Mebibits Per Second
		 */
		public static double toMebibitsPerSecond(double value) {
			return value / 0.000000131072;
		}
	}
}
