// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

package com.putridparrot.units;

/**
 * Fuel Economy conversion functions
 */
public final class FuelEconomy {
	/**
	 * Kilometre Per Litre conversion functions
	 */
	public static class KilometrePerLitre {
		/**
		 * Converts the supplied Kilometre Per Litre value to US Miles Per Gallon
		 * @param value The Kilometre Per Litre input value
		 * @return The value in US Miles Per Gallon
		 */
		public static double toUSMilesPerGallon(double value) {
			return value * 2.35215;
		}
		/**
		 * Converts the supplied Kilometre Per Litre value to Miles Per Gallon
		 * @param value The Kilometre Per Litre input value
		 * @return The value in Miles Per Gallon
		 */
		public static double toMilesPerGallon(double value) {
			return value * 2.82481;
		}
		/**
		 * Converts the supplied Kilometre Per Litre value to Litres Per 100 Kilometres
		 * @param value The Kilometre Per Litre input value
		 * @return The value in Litres Per 100 Kilometres
		 */
		public static double toLitresPer100Kilometres(double value) {
			return 100.0 / value;
		}
	}
	/**
	 * Litres Per 100 Kilometres conversion functions
	 */
	public static class LitresPer100Kilometres {
		/**
		 * Converts the supplied Litres Per 100 Kilometres value to Kilometre Per Litre
		 * @param value The Litres Per 100 Kilometres input value
		 * @return The value in Kilometre Per Litre
		 */
		public static double toKilometrePerLitre(double value) {
			return 100.0 / value;
		}
		/**
		 * Converts the supplied Litres Per 100 Kilometres value to Miles Per Gallon
		 * @param value The Litres Per 100 Kilometres input value
		 * @return The value in Miles Per Gallon
		 */
		public static double toMilesPerGallon(double value) {
			return 282.481 / value;
		}
		/**
		 * Converts the supplied Litres Per 100 Kilometres value to US Miles Per Gallon
		 * @param value The Litres Per 100 Kilometres input value
		 * @return The value in US Miles Per Gallon
		 */
		public static double toUSMilesPerGallon(double value) {
			return 235.215 / value;
		}
	}
	/**
	 * Miles Per Gallon conversion functions
	 */
	public static class MilesPerGallon {
		/**
		 * Converts the supplied Miles Per Gallon value to Kilometre Per Litre
		 * @param value The Miles Per Gallon input value
		 * @return The value in Kilometre Per Litre
		 */
		public static double toKilometrePerLitre(double value) {
			return value / 2.82481;
		}
		/**
		 * Converts the supplied Miles Per Gallon value to US Miles Per Gallon
		 * @param value The Miles Per Gallon input value
		 * @return The value in US Miles Per Gallon
		 */
		public static double toUSMilesPerGallon(double value) {
			return value / 1.20095;
		}
		/**
		 * Converts the supplied Miles Per Gallon value to Litres Per 100 Kilometres
		 * @param value The Miles Per Gallon input value
		 * @return The value in Litres Per 100 Kilometres
		 */
		public static double toLitresPer100Kilometres(double value) {
			return 282.481 / value;
		}
	}
	/**
	 * US Miles Per Gallon conversion functions
	 */
	public static class USMilesPerGallon {
		/**
		 * Converts the supplied US Miles Per Gallon value to Kilometre Per Litre
		 * @param value The US Miles Per Gallon input value
		 * @return The value in Kilometre Per Litre
		 */
		public static double toKilometrePerLitre(double value) {
			return value / 2.35215;
		}
		/**
		 * Converts the supplied US Miles Per Gallon value to Miles Per Gallon
		 * @param value The US Miles Per Gallon input value
		 * @return The value in Miles Per Gallon
		 */
		public static double toMilesPerGallon(double value) {
			return value * 1.20095;
		}
		/**
		 * Converts the supplied US Miles Per Gallon value to Litres Per 100 Kilometres
		 * @param value The US Miles Per Gallon input value
		 * @return The value in Litres Per 100 Kilometres
		 */
		public static double toLitresPer100Kilometres(double value) {
			return 235.215 / value;
		}
	}
}
