// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

package com.putridparrot.units;

/**
 * Luminous Energy conversion functions
 */
public final class LuminousEnergy {
	/**
	 * LumenHour conversion functions
	 */
	public static class LumenHour {
		/**
		 * Converts the supplied LumenHour value to Talbot
		 * @param value The LumenHour input value
		 * @return The value in Talbot
		 */
		public static double toTalbot(double value) {
			return value * 3600.0;
		}
		/**
		 * Converts the supplied LumenHour value to LumenMinute
		 * @param value The LumenHour input value
		 * @return The value in LumenMinute
		 */
		public static double toLumenMinute(double value) {
			return value * 60.0;
		}
		/**
		 * Converts the supplied LumenHour value to LumenSecond
		 * @param value The LumenHour input value
		 * @return The value in LumenSecond
		 */
		public static double toLumenSecond(double value) {
			return value * 3600.0;
		}
	}
	/**
	 * LumenMinute conversion functions
	 */
	public static class LumenMinute {
		/**
		 * Converts the supplied LumenMinute value to Talbot
		 * @param value The LumenMinute input value
		 * @return The value in Talbot
		 */
		public static double toTalbot(double value) {
			return value * 60.0;
		}
		/**
		 * Converts the supplied LumenMinute value to LumenHour
		 * @param value The LumenMinute input value
		 * @return The value in LumenHour
		 */
		public static double toLumenHour(double value) {
			return value / 60.0;
		}
		/**
		 * Converts the supplied LumenMinute value to LumenSecond
		 * @param value The LumenMinute input value
		 * @return The value in LumenSecond
		 */
		public static double toLumenSecond(double value) {
			return value * 60.0;
		}
	}
	/**
	 * LumenSecond conversion functions
	 */
	public static class LumenSecond {
		/**
		 * Converts the supplied LumenSecond value to Talbot
		 * @param value The LumenSecond input value
		 * @return The value in Talbot
		 */
		public static double toTalbot(double value) {
			return value;
		}
		/**
		 * Converts the supplied LumenSecond value to LumenHour
		 * @param value The LumenSecond input value
		 * @return The value in LumenHour
		 */
		public static double toLumenHour(double value) {
			return value / 3600.0;
		}
		/**
		 * Converts the supplied LumenSecond value to LumenMinute
		 * @param value The LumenSecond input value
		 * @return The value in LumenMinute
		 */
		public static double toLumenMinute(double value) {
			return value / 60.0;
		}
	}
	/**
	 * Talbot conversion functions
	 */
	public static class Talbot {
		/**
		 * Converts the supplied Talbot value to LumenSecond
		 * @param value The Talbot input value
		 * @return The value in LumenSecond
		 */
		public static double toLumenSecond(double value) {
			return value;
		}
		/**
		 * Converts the supplied Talbot value to LumenHour
		 * @param value The Talbot input value
		 * @return The value in LumenHour
		 */
		public static double toLumenHour(double value) {
			return value / 3600.0;
		}
		/**
		 * Converts the supplied Talbot value to LumenMinute
		 * @param value The Talbot input value
		 * @return The value in LumenMinute
		 */
		public static double toLumenMinute(double value) {
			return value / 60.0;
		}
	}
}
