// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

package com.putridparrot.units;

/**
 * Magnetomotive Force conversion functions
 */
public final class MagnetomotiveForce {
	/**
	 * Ampere-turns conversion functions
	 */
	public static class Ampereturns {
		/**
		 * Converts the supplied Ampere-turns value to Gilberts
		 * @param value The Ampere-turns input value
		 * @return The value in Gilberts
		 */
		public static double toGilberts(double value) {
			return value / 0.7957747154595;
		}
	}
	/**
	 * Gilberts conversion functions
	 */
	public static class Gilberts {
		/**
		 * Converts the supplied Gilberts value to Ampere-turns
		 * @param value The Gilberts input value
		 * @return The value in Ampere-turns
		 */
		public static double toAmpereturns(double value) {
			return value * 0.7957747154595;
		}
	}
}
