// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

package com.putridparrot.units;

/**
 * Mass conversion functions
 */
public final class Mass {
	/**
	 * Grams conversion functions
	 */
	public static class Grams {
		/**
		 * Converts the supplied Grams value to Milligrams
		 * @param value The Grams input value
		 * @return The value in Milligrams
		 */
		public static double toMilligrams(double value) {
			return value * 1000.0;
		}
		/**
		 * Converts the supplied Grams value to Kilograms
		 * @param value The Grams input value
		 * @return The value in Kilograms
		 */
		public static double toKilograms(double value) {
			return value / 1000.0;
		}
		/**
		 * Converts the supplied Grams value to Tonnes
		 * @param value The Grams input value
		 * @return The value in Tonnes
		 */
		public static double toTonnes(double value) {
			return value * 1e-6;
		}
		/**
		 * Converts the supplied Grams value to Ounces
		 * @param value The Grams input value
		 * @return The value in Ounces
		 */
		public static double toOunces(double value) {
			return value / 28.3495231;
		}
		/**
		 * Converts the supplied Grams value to Pounds
		 * @param value The Grams input value
		 * @return The value in Pounds
		 */
		public static double toPounds(double value) {
			return value / 453.59237;
		}
		/**
		 * Converts the supplied Grams value to Stones
		 * @param value The Grams input value
		 * @return The value in Stones
		 */
		public static double toStones(double value) {
			return value / 6350.29318;
		}
	}
	/**
	 * Kilograms conversion functions
	 */
	public static class Kilograms {
		/**
		 * Converts the supplied Kilograms value to Milligrams
		 * @param value The Kilograms input value
		 * @return The value in Milligrams
		 */
		public static double toMilligrams(double value) {
			return value * 1e+6;
		}
		/**
		 * Converts the supplied Kilograms value to Grams
		 * @param value The Kilograms input value
		 * @return The value in Grams
		 */
		public static double toGrams(double value) {
			return value * 1000.0;
		}
		/**
		 * Converts the supplied Kilograms value to Tonnes
		 * @param value The Kilograms input value
		 * @return The value in Tonnes
		 */
		public static double toTonnes(double value) {
			return value * 0.001;
		}
		/**
		 * Converts the supplied Kilograms value to Ounces
		 * @param value The Kilograms input value
		 * @return The value in Ounces
		 */
		public static double toOunces(double value) {
			return value * 35.274;
		}
		/**
		 * Converts the supplied Kilograms value to Pounds
		 * @param value The Kilograms input value
		 * @return The value in Pounds
		 */
		public static double toPounds(double value) {
			return value * 2.20462;
		}
		/**
		 * Converts the supplied Kilograms value to Stones
		 * @param value The Kilograms input value
		 * @return The value in Stones
		 */
		public static double toStones(double value) {
			return value * 0.157473;
		}
	}
	/**
	 * Milligrams conversion functions
	 */
	public static class Milligrams {
		/**
		 * Converts the supplied Milligrams value to Grams
		 * @param value The Milligrams input value
		 * @return The value in Grams
		 */
		public static double toGrams(double value) {
			return value / 1000.0;
		}
		/**
		 * Converts the supplied Milligrams value to Kilograms
		 * @param value The Milligrams input value
		 * @return The value in Kilograms
		 */
		public static double toKilograms(double value) {
			return value / 1e+6;
		}
		/**
		 * Converts the supplied Milligrams value to Tonnes
		 * @param value The Milligrams input value
		 * @return The value in Tonnes
		 */
		public static double toTonnes(double value) {
			return value / 1e+9;
		}
		/**
		 * Converts the supplied Milligrams value to Ounces
		 * @param value The Milligrams input value
		 * @return The value in Ounces
		 */
		public static double toOunces(double value) {
			return value / 28349.5231;
		}
		/**
		 * Converts the supplied Milligrams value to Pounds
		 * @param value The Milligrams input value
		 * @return The value in Pounds
		 */
		public static double toPounds(double value) {
			return value / 453592.37;
		}
		/**
		 * Converts the supplied Milligrams value to Stones
		 * @param value The Milligrams input value
		 * @return The value in Stones
		 */
		public static double toStones(double value) {
			return value / 6350293.18;
		}
	}
	/**
	 * Ounces conversion functions
	 */
	public static class Ounces {
		/**
		 * Converts the supplied Ounces value to Milligrams
		 * @param value The Ounces input value
		 * @return The value in Milligrams
		 */
		public static double toMilligrams(double value) {
			return value * 28349.5231;
		}
		/**
		 * Converts the supplied Ounces value to Grams
		 * @param value The Ounces input value
		 * @return The value in Grams
		 */
		public static double toGrams(double value) {
			return value * 28.3495231;
		}
		/**
		 * Converts the supplied Ounces value to Kilograms
		 * @param value The Ounces input value
		 * @return The value in Kilograms
		 */
		public static double toKilograms(double value) {
			return value * 0.0283495;
		}
		/**
		 * Converts the supplied Ounces value to Tonnes
		 * @param value The Ounces input value
		 * @return The value in Tonnes
		 */
		public static double toTonnes(double value) {
			return value * 0.0000283495231;
		}
		/**
		 * Converts the supplied Ounces value to Pounds
		 * @param value The Ounces input value
		 * @return The value in Pounds
		 */
		public static double toPounds(double value) {
			return value * 0.0625;
		}
		/**
		 * Converts the supplied Ounces value to Stones
		 * @param value The Ounces input value
		 * @return The value in Stones
		 */
		public static double toStones(double value) {
			return value * 0.00446429;
		}
	}
	/**
	 * Pounds conversion functions
	 */
	public static class Pounds {
		/**
		 * Converts the supplied Pounds value to Milligrams
		 * @param value The Pounds input value
		 * @return The value in Milligrams
		 */
		public static double toMilligrams(double value) {
			return value * 453592.37;
		}
		/**
		 * Converts the supplied Pounds value to Grams
		 * @param value The Pounds input value
		 * @return The value in Grams
		 */
		public static double toGrams(double value) {
			return value * 453.59237;
		}
		/**
		 * Converts the supplied Pounds value to Kilograms
		 * @param value The Pounds input value
		 * @return The value in Kilograms
		 */
		public static double toKilograms(double value) {
			return value * 0.453592;
		}
		/**
		 * Converts the supplied Pounds value to Tonnes
		 * @param value The Pounds input value
		 * @return The value in Tonnes
		 */
		public static double toTonnes(double value) {
			return value / 2204.62;
		}
		/**
		 * Converts the supplied Pounds value to Ounces
		 * @param value The Pounds input value
		 * @return The value in Ounces
		 */
		public static double toOunces(double value) {
			return value * 16.0;
		}
		/**
		 * Converts the supplied Pounds value to Stones
		 * @param value The Pounds input value
		 * @return The value in Stones
		 */
		public static double toStones(double value) {
			return value / 14.0;
		}
	}
	/**
	 * Stones conversion functions
	 */
	public static class Stones {
		/**
		 * Converts the supplied Stones value to Milligrams
		 * @param value The Stones input value
		 * @return The value in Milligrams
		 */
		public static double toMilligrams(double value) {
			return value * 6350293.18;
		}
		/**
		 * Converts the supplied Stones value to Grams
		 * @param value The Stones input value
		 * @return The value in Grams
		 */
		public static double toGrams(double value) {
			return value * 6350.29318;
		}
		/**
		 * Converts the supplied Stones value to Kilograms
		 * @param value The Stones input value
		 * @return The value in Kilograms
		 */
		public static double toKilograms(double value) {
			return value * 6.35029;
		}
		/**
		 * Converts the supplied Stones value to Tonnes
		 * @param value The Stones input value
		 * @return The value in Tonnes
		 */
		public static double toTonnes(double value) {
			return value * 0.00635029;
		}
		/**
		 * Converts the supplied Stones value to Ounces
		 * @param value The Stones input value
		 * @return The value in Ounces
		 */
		public static double toOunces(double value) {
			return value * 224.0;
		}
		/**
		 * Converts the supplied Stones value to Pounds
		 * @param value The Stones input value
		 * @return The value in Pounds
		 */
		public static double toPounds(double value) {
			return value * 14.0;
		}
	}
	/**
	 * Tonnes conversion functions
	 */
	public static class Tonnes {
		/**
		 * Converts the supplied Tonnes value to Milligrams
		 * @param value The Tonnes input value
		 * @return The value in Milligrams
		 */
		public static double toMilligrams(double value) {
			return value * 1e+9;
		}
		/**
		 * Converts the supplied Tonnes value to Grams
		 * @param value The Tonnes input value
		 * @return The value in Grams
		 */
		public static double toGrams(double value) {
			return value * 1e+6;
		}
		/**
		 * Converts the supplied Tonnes value to Kilograms
		 * @param value The Tonnes input value
		 * @return The value in Kilograms
		 */
		public static double toKilograms(double value) {
			return value * 1000.0;
		}
		/**
		 * Converts the supplied Tonnes value to Ounces
		 * @param value The Tonnes input value
		 * @return The value in Ounces
		 */
		public static double toOunces(double value) {
			return value / 0.0000283495231;
		}
		/**
		 * Converts the supplied Tonnes value to Pounds
		 * @param value The Tonnes input value
		 * @return The value in Pounds
		 */
		public static double toPounds(double value) {
			return value * 2204.62;
		}
		/**
		 * Converts the supplied Tonnes value to Stones
		 * @param value The Tonnes input value
		 * @return The value in Stones
		 */
		public static double toStones(double value) {
			return value * 157.473;
		}
	}
}
