// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

package com.putridparrot.units;

/**
 * Time conversion functions
 */
public final class Time {
	/**
	 * Centuries conversion functions
	 */
	public static class Centuries {
		/**
		 * Converts the supplied Centuries value to Seconds
		 * @param value The Centuries input value
		 * @return The value in Seconds
		 */
		public static double toSeconds(double value) {
			return value * 3.154e+9;
		}
		/**
		 * Converts the supplied Centuries value to Minutes
		 * @param value The Centuries input value
		 * @return The value in Minutes
		 */
		public static double toMinutes(double value) {
			return value * 5.256e+7;
		}
		/**
		 * Converts the supplied Centuries value to Hours
		 * @param value The Centuries input value
		 * @return The value in Hours
		 */
		public static double toHours(double value) {
			return value * 876000.0;
		}
		/**
		 * Converts the supplied Centuries value to Days
		 * @param value The Centuries input value
		 * @return The value in Days
		 */
		public static double toDays(double value) {
			return value * 36500.0;
		}
		/**
		 * Converts the supplied Centuries value to Weeks
		 * @param value The Centuries input value
		 * @return The value in Weeks
		 */
		public static double toWeeks(double value) {
			return value * 5214.29;
		}
		/**
		 * Converts the supplied Centuries value to Months
		 * @param value The Centuries input value
		 * @return The value in Months
		 */
		public static double toMonths(double value) {
			return value * 1200.0;
		}
		/**
		 * Converts the supplied Centuries value to Years
		 * @param value The Centuries input value
		 * @return The value in Years
		 */
		public static double toYears(double value) {
			return value * 100.0;
		}
		/**
		 * Converts the supplied Centuries value to Decades
		 * @param value The Centuries input value
		 * @return The value in Decades
		 */
		public static double toDecades(double value) {
			return value * 10.0;
		}
	}
	/**
	 * Days conversion functions
	 */
	public static class Days {
		/**
		 * Converts the supplied Days value to Seconds
		 * @param value The Days input value
		 * @return The value in Seconds
		 */
		public static double toSeconds(double value) {
			return value * 86400.0;
		}
		/**
		 * Converts the supplied Days value to Minutes
		 * @param value The Days input value
		 * @return The value in Minutes
		 */
		public static double toMinutes(double value) {
			return value * 1440.0;
		}
		/**
		 * Converts the supplied Days value to Hours
		 * @param value The Days input value
		 * @return The value in Hours
		 */
		public static double toHours(double value) {
			return value * 24.0;
		}
		/**
		 * Converts the supplied Days value to Weeks
		 * @param value The Days input value
		 * @return The value in Weeks
		 */
		public static double toWeeks(double value) {
			return value / 7.0;
		}
		/**
		 * Converts the supplied Days value to Months
		 * @param value The Days input value
		 * @return The value in Months
		 */
		public static double toMonths(double value) {
			return value / 30.4167;
		}
		/**
		 * Converts the supplied Days value to Years
		 * @param value The Days input value
		 * @return The value in Years
		 */
		public static double toYears(double value) {
			return value / 365.0;
		}
		/**
		 * Converts the supplied Days value to Decades
		 * @param value The Days input value
		 * @return The value in Decades
		 */
		public static double toDecades(double value) {
			return value / 3650.0;
		}
		/**
		 * Converts the supplied Days value to Centuries
		 * @param value The Days input value
		 * @return The value in Centuries
		 */
		public static double toCenturies(double value) {
			return value / 36500.0;
		}
	}
	/**
	 * Decades conversion functions
	 */
	public static class Decades {
		/**
		 * Converts the supplied Decades value to Seconds
		 * @param value The Decades input value
		 * @return The value in Seconds
		 */
		public static double toSeconds(double value) {
			return value * 3.154e+8;
		}
		/**
		 * Converts the supplied Decades value to Minutes
		 * @param value The Decades input value
		 * @return The value in Minutes
		 */
		public static double toMinutes(double value) {
			return value * 5.256e+6;
		}
		/**
		 * Converts the supplied Decades value to Hours
		 * @param value The Decades input value
		 * @return The value in Hours
		 */
		public static double toHours(double value) {
			return value * 87600.0;
		}
		/**
		 * Converts the supplied Decades value to Days
		 * @param value The Decades input value
		 * @return The value in Days
		 */
		public static double toDays(double value) {
			return value * 3650.0;
		}
		/**
		 * Converts the supplied Decades value to Weeks
		 * @param value The Decades input value
		 * @return The value in Weeks
		 */
		public static double toWeeks(double value) {
			return value * 521.429;
		}
		/**
		 * Converts the supplied Decades value to Months
		 * @param value The Decades input value
		 * @return The value in Months
		 */
		public static double toMonths(double value) {
			return value * 120.0;
		}
		/**
		 * Converts the supplied Decades value to Years
		 * @param value The Decades input value
		 * @return The value in Years
		 */
		public static double toYears(double value) {
			return value * 10.0;
		}
		/**
		 * Converts the supplied Decades value to Centuries
		 * @param value The Decades input value
		 * @return The value in Centuries
		 */
		public static double toCenturies(double value) {
			return value / 10.0;
		}
	}
	/**
	 * Hours conversion functions
	 */
	public static class Hours {
		/**
		 * Converts the supplied Hours value to Seconds
		 * @param value The Hours input value
		 * @return The value in Seconds
		 */
		public static double toSeconds(double value) {
			return value * 3600.0;
		}
		/**
		 * Converts the supplied Hours value to Minutes
		 * @param value The Hours input value
		 * @return The value in Minutes
		 */
		public static double toMinutes(double value) {
			return value * 60.0;
		}
		/**
		 * Converts the supplied Hours value to Days
		 * @param value The Hours input value
		 * @return The value in Days
		 */
		public static double toDays(double value) {
			return value / 24.0;
		}
		/**
		 * Converts the supplied Hours value to Weeks
		 * @param value The Hours input value
		 * @return The value in Weeks
		 */
		public static double toWeeks(double value) {
			return value / 168.0;
		}
		/**
		 * Converts the supplied Hours value to Months
		 * @param value The Hours input value
		 * @return The value in Months
		 */
		public static double toMonths(double value) {
			return value / 730.001;
		}
		/**
		 * Converts the supplied Hours value to Years
		 * @param value The Hours input value
		 * @return The value in Years
		 */
		public static double toYears(double value) {
			return value / 8760.0;
		}
		/**
		 * Converts the supplied Hours value to Decades
		 * @param value The Hours input value
		 * @return The value in Decades
		 */
		public static double toDecades(double value) {
			return value / 87600.0;
		}
		/**
		 * Converts the supplied Hours value to Centuries
		 * @param value The Hours input value
		 * @return The value in Centuries
		 */
		public static double toCenturies(double value) {
			return value / 876000.0;
		}
	}
	/**
	 * Minutes conversion functions
	 */
	public static class Minutes {
		/**
		 * Converts the supplied Minutes value to Seconds
		 * @param value The Minutes input value
		 * @return The value in Seconds
		 */
		public static double toSeconds(double value) {
			return value * 60.0;
		}
		/**
		 * Converts the supplied Minutes value to Hours
		 * @param value The Minutes input value
		 * @return The value in Hours
		 */
		public static double toHours(double value) {
			return value / 60.0;
		}
		/**
		 * Converts the supplied Minutes value to Days
		 * @param value The Minutes input value
		 * @return The value in Days
		 */
		public static double toDays(double value) {
			return value / 1440.0;
		}
		/**
		 * Converts the supplied Minutes value to Weeks
		 * @param value The Minutes input value
		 * @return The value in Weeks
		 */
		public static double toWeeks(double value) {
			return value / 10080.0;
		}
		/**
		 * Converts the supplied Minutes value to Months
		 * @param value The Minutes input value
		 * @return The value in Months
		 */
		public static double toMonths(double value) {
			return value / 43800.0;
		}
		/**
		 * Converts the supplied Minutes value to Years
		 * @param value The Minutes input value
		 * @return The value in Years
		 */
		public static double toYears(double value) {
			return value / 525600.0;
		}
		/**
		 * Converts the supplied Minutes value to Decades
		 * @param value The Minutes input value
		 * @return The value in Decades
		 */
		public static double toDecades(double value) {
			return value / 5.256e+6;
		}
		/**
		 * Converts the supplied Minutes value to Centuries
		 * @param value The Minutes input value
		 * @return The value in Centuries
		 */
		public static double toCenturies(double value) {
			return value / 5.256e+7;
		}
	}
	/**
	 * Months conversion functions
	 */
	public static class Months {
		/**
		 * Converts the supplied Months value to Seconds
		 * @param value The Months input value
		 * @return The value in Seconds
		 */
		public static double toSeconds(double value) {
			return value * 2.628e+6;
		}
		/**
		 * Converts the supplied Months value to Minutes
		 * @param value The Months input value
		 * @return The value in Minutes
		 */
		public static double toMinutes(double value) {
			return value * 43800.0;
		}
		/**
		 * Converts the supplied Months value to Hours
		 * @param value The Months input value
		 * @return The value in Hours
		 */
		public static double toHours(double value) {
			return value * 730.001;
		}
		/**
		 * Converts the supplied Months value to Days
		 * @param value The Months input value
		 * @return The value in Days
		 */
		public static double toDays(double value) {
			return value * 30.4167;
		}
		/**
		 * Converts the supplied Months value to Weeks
		 * @param value The Months input value
		 * @return The value in Weeks
		 */
		public static double toWeeks(double value) {
			return value * 4.34524;
		}
		/**
		 * Converts the supplied Months value to Years
		 * @param value The Months input value
		 * @return The value in Years
		 */
		public static double toYears(double value) {
			return value / 12.0;
		}
		/**
		 * Converts the supplied Months value to Decades
		 * @param value The Months input value
		 * @return The value in Decades
		 */
		public static double toDecades(double value) {
			return value / 120.0;
		}
		/**
		 * Converts the supplied Months value to Centuries
		 * @param value The Months input value
		 * @return The value in Centuries
		 */
		public static double toCenturies(double value) {
			return value / 1200.0;
		}
	}
	/**
	 * Seconds conversion functions
	 */
	public static class Seconds {
		/**
		 * Converts the supplied Seconds value to Minutes
		 * @param value The Seconds input value
		 * @return The value in Minutes
		 */
		public static double toMinutes(double value) {
			return value / 60.0;
		}
		/**
		 * Converts the supplied Seconds value to Hours
		 * @param value The Seconds input value
		 * @return The value in Hours
		 */
		public static double toHours(double value) {
			return value / 3600.0;
		}
		/**
		 * Converts the supplied Seconds value to Days
		 * @param value The Seconds input value
		 * @return The value in Days
		 */
		public static double toDays(double value) {
			return value / 86400.0;
		}
		/**
		 * Converts the supplied Seconds value to Weeks
		 * @param value The Seconds input value
		 * @return The value in Weeks
		 */
		public static double toWeeks(double value) {
			return value / 604800.0;
		}
		/**
		 * Converts the supplied Seconds value to Months
		 * @param value The Seconds input value
		 * @return The value in Months
		 */
		public static double toMonths(double value) {
			return value / 2.628e+6;
		}
		/**
		 * Converts the supplied Seconds value to Years
		 * @param value The Seconds input value
		 * @return The value in Years
		 */
		public static double toYears(double value) {
			return value / 3.1536e+7;
		}
		/**
		 * Converts the supplied Seconds value to Decades
		 * @param value The Seconds input value
		 * @return The value in Decades
		 */
		public static double toDecades(double value) {
			return value / 3.154e+8;
		}
		/**
		 * Converts the supplied Seconds value to Centuries
		 * @param value The Seconds input value
		 * @return The value in Centuries
		 */
		public static double toCenturies(double value) {
			return value / 3.154e+9;
		}
	}
	/**
	 * Weeks conversion functions
	 */
	public static class Weeks {
		/**
		 * Converts the supplied Weeks value to Seconds
		 * @param value The Weeks input value
		 * @return The value in Seconds
		 */
		public static double toSeconds(double value) {
			return value * 604800.0;
		}
		/**
		 * Converts the supplied Weeks value to Minutes
		 * @param value The Weeks input value
		 * @return The value in Minutes
		 */
		public static double toMinutes(double value) {
			return value * 10080.0;
		}
		/**
		 * Converts the supplied Weeks value to Hours
		 * @param value The Weeks input value
		 * @return The value in Hours
		 */
		public static double toHours(double value) {
			return value * 168.0;
		}
		/**
		 * Converts the supplied Weeks value to Days
		 * @param value The Weeks input value
		 * @return The value in Days
		 */
		public static double toDays(double value) {
			return value * 7.0;
		}
		/**
		 * Converts the supplied Weeks value to Months
		 * @param value The Weeks input value
		 * @return The value in Months
		 */
		public static double toMonths(double value) {
			return value / 4.34524;
		}
		/**
		 * Converts the supplied Weeks value to Years
		 * @param value The Weeks input value
		 * @return The value in Years
		 */
		public static double toYears(double value) {
			return value / 52.143;
		}
		/**
		 * Converts the supplied Weeks value to Decades
		 * @param value The Weeks input value
		 * @return The value in Decades
		 */
		public static double toDecades(double value) {
			return value / 521.429;
		}
		/**
		 * Converts the supplied Weeks value to Centuries
		 * @param value The Weeks input value
		 * @return The value in Centuries
		 */
		public static double toCenturies(double value) {
			return value / 5214.29;
		}
	}
	/**
	 * Years conversion functions
	 */
	public static class Years {
		/**
		 * Converts the supplied Years value to Seconds
		 * @param value The Years input value
		 * @return The value in Seconds
		 */
		public static double toSeconds(double value) {
			return value * 3.1536e+7;
		}
		/**
		 * Converts the supplied Years value to Minutes
		 * @param value The Years input value
		 * @return The value in Minutes
		 */
		public static double toMinutes(double value) {
			return value * 525600.0;
		}
		/**
		 * Converts the supplied Years value to Hours
		 * @param value The Years input value
		 * @return The value in Hours
		 */
		public static double toHours(double value) {
			return value * 8760.0;
		}
		/**
		 * Converts the supplied Years value to Days
		 * @param value The Years input value
		 * @return The value in Days
		 */
		public static double toDays(double value) {
			return value * 365.0;
		}
		/**
		 * Converts the supplied Years value to Weeks
		 * @param value The Years input value
		 * @return The value in Weeks
		 */
		public static double toWeeks(double value) {
			return value * 52.143;
		}
		/**
		 * Converts the supplied Years value to Months
		 * @param value The Years input value
		 * @return The value in Months
		 */
		public static double toMonths(double value) {
			return value * 12.0;
		}
		/**
		 * Converts the supplied Years value to Decades
		 * @param value The Years input value
		 * @return The value in Decades
		 */
		public static double toDecades(double value) {
			return value / 10.0;
		}
		/**
		 * Converts the supplied Years value to Centuries
		 * @param value The Years input value
		 * @return The value in Centuries
		 */
		public static double toCenturies(double value) {
			return value / 100.0;
		}
	}
}
