// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

package com.putridparrot.units;

import org.junit.jupiter.api.Nested;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class LuminousEnergyTests {
	@Nested
	public class LumenHourTests {
		@ParameterizedTest
		@CsvSource({ "9.0,32400.0","1.2,4320.0","4.0,14400.0" })
		public void testConvertKnownLumenHourToTalbot(double input, double expectation) {
			final double result = LuminousEnergy.LumenHour.toTalbot(input);
			assertEquals(expectation, result, 0.01);
		}

		@ParameterizedTest
		@CsvSource({ "1.2,72.0","0.8,48.0","109.00,6540" })
		public void testConvertKnownLumenHourToLumenMinute(double input, double expectation) {
			final double result = LuminousEnergy.LumenHour.toLumenMinute(input);
			assertEquals(expectation, result, 0.01);
		}

		@ParameterizedTest
		@CsvSource({ "109.0,392400.0","6.1,21960.0","0.7,2520.0" })
		public void testConvertKnownLumenHourToLumenSecond(double input, double expectation) {
			final double result = LuminousEnergy.LumenHour.toLumenSecond(input);
			assertEquals(expectation, result, 0.01);
		}

	}
	@Nested
	public class LumenMinuteTests {
		@ParameterizedTest
		@CsvSource({ "0.7,42.0","678.0,40680.0","89.0,5340.0" })
		public void testConvertKnownLumenMinuteToTalbot(double input, double expectation) {
			final double result = LuminousEnergy.LumenMinute.toTalbot(input);
			assertEquals(expectation, result, 0.01);
		}

		@ParameterizedTest
		@CsvSource({ "89.0,1.4833","9.0,0.15","0.123,0.00205" })
		public void testConvertKnownLumenMinuteToLumenHour(double input, double expectation) {
			final double result = LuminousEnergy.LumenMinute.toLumenHour(input);
			assertEquals(expectation, result, 0.01);
		}

		@ParameterizedTest
		@CsvSource({ "0.123,7.38","8000.0,480000.0","34.1,2046.0" })
		public void testConvertKnownLumenMinuteToLumenSecond(double input, double expectation) {
			final double result = LuminousEnergy.LumenMinute.toLumenSecond(input);
			assertEquals(expectation, result, 0.01);
		}

	}
	@Nested
	public class LumenSecondTests {
		@ParameterizedTest
		@CsvSource({ "190.0,190.0","0.6,0.6","5000.0,5000.0" })
		public void testConvertKnownLumenSecondToTalbot(double input, double expectation) {
			final double result = LuminousEnergy.LumenSecond.toTalbot(input);
			assertEquals(expectation, result, 0.01);
		}

		@ParameterizedTest
		@CsvSource({ "190.0,0.052778","200600.0,55.7222","1234.0,0.342778" })
		public void testConvertKnownLumenSecondToLumenHour(double input, double expectation) {
			final double result = LuminousEnergy.LumenSecond.toLumenHour(input);
			assertEquals(expectation, result, 0.01);
		}

		@ParameterizedTest
		@CsvSource({ "10900.0,181.6667","50.3,0.83833","276.0,4.6" })
		public void testConvertKnownLumenSecondToLumenMinute(double input, double expectation) {
			final double result = LuminousEnergy.LumenSecond.toLumenMinute(input);
			assertEquals(expectation, result, 0.01);
		}

	}
	@Nested
	public class TalbotTests {
		@ParameterizedTest
		@CsvSource({ "100.0,100.0","0.9,0.9","23.1,23.1" })
		public void testConvertKnownTalbotToLumenSecond(double input, double expectation) {
			final double result = LuminousEnergy.Talbot.toLumenSecond(input);
			assertEquals(expectation, result, 0.01);
		}

		@ParameterizedTest
		@CsvSource({ "800.0,0.222","6789.0,1.885833","10900.0,3.027778" })
		public void testConvertKnownTalbotToLumenHour(double input, double expectation) {
			final double result = LuminousEnergy.Talbot.toLumenHour(input);
			assertEquals(expectation, result, 0.01);
		}

		@ParameterizedTest
		@CsvSource({ "900.0,15.0","78.9,1.315","1500.0,25.0" })
		public void testConvertKnownTalbotToLumenMinute(double input, double expectation) {
			final double result = LuminousEnergy.Talbot.toLumenMinute(input);
			assertEquals(expectation, result, 0.01);
		}

	}
}
